/**
 * SOURCE OF TRUTH for this specific project
 * Generated by analyzing: apps/web/src/content/
 * Date: 2026-02-01
 *
 * ⚠️ This file is project-specific and must be regenerated
 * if the content structure changes.
 *
 * Project: outkast-sanity-astro
 * Collections discovered: 5
 * Total fields across all collections: 22 unique fields
 */

// Shared, optional `seo` object declaration. Kept in parity with the Sanity
// `seo` object-type (apps/studio/schemas/objects/seo.ts), the Zod `seoSchema`
// (apps/web/src/content.config.ts) and the datalayer types/queries/transforms.
// Optional and additive: the migration does NOT set it (existing markdown has
// no `seo`), so nothing breaks on a missing value.
const seoField = {
  type: "object",
  required: false,
  shape: {
    metaDescription: { type: "text", required: false },
    noindex: { type: "boolean", required: false },
    canonicalUrl: { type: "url", required: false },
    ogImage: {
      type: "object",
      required: false,
      shape: {
        url: { type: "image", required: false },
        alt: { type: "string", required: false },
      },
    },
  },
} as const;

export const PROJECT_COLLECTIONS = {
  "team": {
    sanityType: "teamMember",
    fields: {
      name: { type: "string", required: true },
      slug: { type: "slug", required: false }, // URL segment under /team/ (voornaam); fallback: _id-afleiding
      role: { type: "string", required: true },
      intro: { type: "text", required: true },
      education: { type: "array", itemType: "string", required: true },
      experience: { type: "array", itemType: "string", required: true },
      avatar: {
        type: "object",
        required: true,
        shape: {
          url: { type: "image", required: true },
          alt: { type: "string", required: true }
        }
      },
      body: { type: "markdown", required: true } // Markdown content
    },
    relationships: {}
  },
  "work": {
    sanityType: "workItem",
    fields: {
      slug: { type: "slug", required: true }, // URL segment under /work/
      link: { type: "string", required: false },
      company: { type: "string", required: false },
      year: { type: "string", required: false },
      client: { type: "string", required: false },
      work: { type: "string", required: true },
      bijschrift: { type: "string", required: false },
      statement: { type: "string", required: false },
      credits: {
        type: "array",
        itemType: "object",
        required: false,
        shape: {
          name: { type: "string", required: true },
          role: { type: "string", required: true }
        }
      },
      thumbnail: {
        type: "object",
        required: true,
        shape: {
          url: { type: "image", required: true },
          alt: { type: "string", required: true }
        }
      },
      body: { type: "portableText", required: false }, // Portable Text array (rich text + shared blocks)
      seo: seoField // Optional shared SEO object (additive)
    },
    relationships: {}
  },
  "services": {
    sanityType: "service",
    fields: {
      service: { type: "string", required: true },
      slug: { type: "slug", required: true }, // URL segment under /services/
      description: { type: "text", required: true },
      body: { type: "portableText", required: true }, // Portable Text array (rich text + shared blocks)
      thumbnail: {
        type: "object",
        required: false, // Optioneel — miniatuur voor het diensten-overzicht
        shape: {
          url: { type: "image", required: false },
          alt: { type: "string", required: false }
        }
      },
      categories: { type: "array", itemType: "string", required: false }, // Optioneel — filtercategorieën
      seo: seoField // Optional shared SEO object (additive)
    },
    relationships: {}
  },
  "posts": {
    sanityType: "post",
    fields: {
      title: { type: "string", required: true },
      slug: { type: "slug", required: true }, // URL segment under /blog/
      pubDate: { type: "date", required: true },
      description: { type: "text", required: true },
      author: { type: "string", required: true },
      image: {
        type: "object",
        required: true,
        shape: {
          url: { type: "image", required: true },
          alt: { type: "string", required: true }
        }
      },
      tags: { type: "array", itemType: "string", required: true },
      body: { type: "portableText", required: true }, // Portable Text array (rich text + shared blocks)
      seo: seoField // Optional shared SEO object (additive)
    },
    relationships: {}
  },
  "legal": {
    sanityType: "legalPage",
    fields: {
      page: { type: "string", required: true },
      pubDate: { type: "date", required: true },
      body: { type: "portableText", required: true }, // Portable Text array (rich text + shared blocks)
      seo: seoField // Optional shared SEO object (additive)
    },
    relationships: {}
  }
} as const;

// Auto-generated types
export type CollectionName = keyof typeof PROJECT_COLLECTIONS;
export type SanityTypeName = typeof PROJECT_COLLECTIONS[CollectionName]['sanityType'];

// Collection name to Sanity type mapping
export const collectionToSanityType: Record<CollectionName, SanityTypeName> = {
  team: "teamMember",
  work: "workItem",
  services: "service",
  posts: "post",
  legal: "legalPage"
};

// Sanity type to collection name mapping (for reverse lookups)
export const sanityTypeToCollection: Record<SanityTypeName, CollectionName> = {
  teamMember: "team",
  workItem: "work",
  service: "services",
  post: "posts",
  legalPage: "legal"
};

// Validation helper
export function validateCollection(collectionName: string): collectionName is CollectionName {
  return collectionName in PROJECT_COLLECTIONS;
}

// Field count summary for validation
export const COLLECTION_STATS = {
  totalCollections: 5,
  collections: {
    team: { fieldCount: 8 }, // name, slug, role, intro, education, experience, avatar, body
    work: { fieldCount: 10 }, // slug, link, company, year, client, work, credits, thumbnail, body, seo
    services: { fieldCount: 7 }, // service, slug, description, body, thumbnail, categories, seo
    posts: { fieldCount: 9 }, // title, slug, pubDate, description, author, image, tags, body, seo
    legal: { fieldCount: 4 } // page, pubDate, body, seo
  }
} as const;
